#pragma once

#define VCADDR_BASE    0x40000000

#ifdef RPI4
#define HD_BUS_BASE                (0x7E000000) //peripheral address in gpu
#define HDMI_MAI_DATA_BUS          ((volatile uint32_t *)(HD_BUS_BASE + 0xF2001C))
//HD BASE
#define HDMI_M_CTL                 ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))  //most not yet defined
#define HDMI_MAI_CTL               ((volatile uint32_t *)(_get_peripheral_base() + 0xF20010))
#define HDMI_MAI_THR               ((volatile uint32_t *)(_get_peripheral_base() + 0xF20014))
#define HDMI_MAI_FMT               ((volatile uint32_t *)(_get_peripheral_base() + 0xF20018))
#define HDMI_MAI_DATA              ((volatile uint32_t *)(_get_peripheral_base() + 0xF2001C))
#define HDMI_MAI_SMP               ((volatile uint32_t *)(_get_peripheral_base() + 0xF20020))
#define HDMI_VID_CTL               ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_CSC_CTL               ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_CSC_12_11             ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_CSC_14_13             ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_CSC_22_21             ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_CSC_24_23             ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_CSC_32_31             ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_CSC_34_33             ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))
#define HDMI_FRAME_COUNT           ((volatile uint32_t *)(_get_peripheral_base() + 0xF20000))

//HDMI BASE
#define HDMI_CORE_REV              ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700)) //most not yet defined
#define HDMI_SW_RESET_CONTROL      ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_HOTPLUG_INT           ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_HOTPLUG               ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_FIFO_CTL              ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_MAI_CHANNEL_MAP       ((volatile uint32_t *)(_get_peripheral_base() + 0xF0079C))
#define HDMI_MAI_CONFIG            ((volatile uint32_t *)(_get_peripheral_base() + 0xF007A0))
#define HDMI_MAI_FORMAT            ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_AUDIO_PACKET_CONFIG   ((volatile uint32_t *)(_get_peripheral_base() + 0xF007B8))
#define HDMI_RAM_PACKET_CONFIG     ((volatile uint32_t *)(_get_peripheral_base() + 0xF007BC))
#define HDMI_RAM_PACKET_STATUS     ((volatile uint32_t *)(_get_peripheral_base() + 0xF007C4))
#define HDMI_CRP_CFG               ((volatile uint32_t *)(_get_peripheral_base() + 0xF007C8))
#define HDMI_CTS_0                 ((volatile uint32_t *)(_get_peripheral_base() + 0xF007CC))
#define HDMI_CTS_1                 ((volatile uint32_t *)(_get_peripheral_base() + 0xF007D0))
#define HDMI_SCHEDULER_CONTROL     ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_HORZA                 ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_HORZB                 ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_VERTA0                ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_VERTB0                ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_VERTA1                ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_VERTB1                ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CNTRL_1           ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CNTRL_2           ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CNTRL_3           ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CNTRL_4           ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CNTRL_5           ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_TX_DATA_1         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_TX_DATA_2         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_TX_DATA_3         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_TX_DATA_4         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_RX_DATA_1         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_RX_DATA_2         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_RX_DATA_3         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_RX_DATA_4         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_TX_PHY_RESET_CTL      ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_TX_PHY_CTL_0          ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CPU_STATUS        ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CPU_SET           ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CPU_CLEAR         ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CPU_MASK_STATUS   ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CPU_MASK_SET      ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_CEC_CPU_MASK_CLEAR    ((volatile uint32_t *)(_get_peripheral_base() + 0xF00700))
#define HDMI_RAM_PACKET_START      ((volatile uint32_t *)(_get_peripheral_base() + 0xF01B90))
#define HDMI_RAM_PACKET(x, i)      ((volatile uint32_t *)(_get_peripheral_base() + 0xF01B90 + (0x24 * (x) + (0x4 * (i)))))

#else

#define HD_BUS_BASE                (0x7E000000) //peripheral address in gpu
#define HDMI_MAI_DATA_BUS          ((volatile uint32_t *)(HD_BUS_BASE + 0x808020))

#define HDMI_M_CTL                 ((volatile uint32_t *)(_get_peripheral_base() + 0x80800c))
#define HDMI_MAI_CTL               ((volatile uint32_t *)(_get_peripheral_base() + 0x808014))
#define HDMI_MAI_THR               ((volatile uint32_t *)(_get_peripheral_base() + 0x808018))
#define HDMI_MAI_FMT               ((volatile uint32_t *)(_get_peripheral_base() + 0x80801c))
#define HDMI_MAI_DATA              ((volatile uint32_t *)(_get_peripheral_base() + 0x808020))
#define HDMI_MAI_SMP               ((volatile uint32_t *)(_get_peripheral_base() + 0x80802c))
#define HDMI_VID_CTL               ((volatile uint32_t *)(_get_peripheral_base() + 0x808038))
#define HDMI_CSC_CTL               ((volatile uint32_t *)(_get_peripheral_base() + 0x808040))
#define HDMI_CSC_12_11             ((volatile uint32_t *)(_get_peripheral_base() + 0x808044))
#define HDMI_CSC_14_13             ((volatile uint32_t *)(_get_peripheral_base() + 0x808048))
#define HDMI_CSC_22_21             ((volatile uint32_t *)(_get_peripheral_base() + 0x80804c))
#define HDMI_CSC_24_23             ((volatile uint32_t *)(_get_peripheral_base() + 0x808050))
#define HDMI_CSC_32_31             ((volatile uint32_t *)(_get_peripheral_base() + 0x808054))
#define HDMI_CSC_34_33             ((volatile uint32_t *)(_get_peripheral_base() + 0x808058))
#define HDMI_FRAME_COUNT           ((volatile uint32_t *)(_get_peripheral_base() + 0x808068))


#define HDMI_CORE_REV              ((volatile uint32_t *)(_get_peripheral_base() + 0x902000))
#define HDMI_SW_RESET_CONTROL      ((volatile uint32_t *)(_get_peripheral_base() + 0x902004))
#define HDMI_HOTPLUG_INT           ((volatile uint32_t *)(_get_peripheral_base() + 0x902008))
#define HDMI_HOTPLUG               ((volatile uint32_t *)(_get_peripheral_base() + 0x90200c))
#define HDMI_FIFO_CTL              ((volatile uint32_t *)(_get_peripheral_base() + 0x90205c))
#define HDMI_MAI_CHANNEL_MAP       ((volatile uint32_t *)(_get_peripheral_base() + 0x902090))
#define HDMI_MAI_CONFIG            ((volatile uint32_t *)(_get_peripheral_base() + 0x902094))
#define HDMI_MAI_FORMAT            ((volatile uint32_t *)(_get_peripheral_base() + 0x902098))
#define HDMI_AUDIO_PACKET_CONFIG   ((volatile uint32_t *)(_get_peripheral_base() + 0x90209c))
#define HDMI_RAM_PACKET_CONFIG     ((volatile uint32_t *)(_get_peripheral_base() + 0x9020a0))
#define HDMI_RAM_PACKET_STATUS     ((volatile uint32_t *)(_get_peripheral_base() + 0x9020a4))
#define HDMI_CRP_CFG               ((volatile uint32_t *)(_get_peripheral_base() + 0x9020a8))
#define HDMI_CTS_0                 ((volatile uint32_t *)(_get_peripheral_base() + 0x9020ac))
#define HDMI_CTS_1                 ((volatile uint32_t *)(_get_peripheral_base() + 0x9020b0))
#define HDMI_SCHEDULER_CONTROL     ((volatile uint32_t *)(_get_peripheral_base() + 0x9020c0))
#define HDMI_HORZA                 ((volatile uint32_t *)(_get_peripheral_base() + 0x9020c4))
#define HDMI_HORZB                 ((volatile uint32_t *)(_get_peripheral_base() + 0x9020c8))
#define HDMI_VERTA0                ((volatile uint32_t *)(_get_peripheral_base() + 0x9020cc))
#define HDMI_VERTB0                ((volatile uint32_t *)(_get_peripheral_base() + 0x9020d0))
#define HDMI_VERTA1                ((volatile uint32_t *)(_get_peripheral_base() + 0x9020d4))
#define HDMI_VERTB1                ((volatile uint32_t *)(_get_peripheral_base() + 0x9020d8))
#define HDMI_CEC_CNTRL_1           ((volatile uint32_t *)(_get_peripheral_base() + 0x9020e8))
#define HDMI_CEC_CNTRL_2           ((volatile uint32_t *)(_get_peripheral_base() + 0x9020ec))
#define HDMI_CEC_CNTRL_3           ((volatile uint32_t *)(_get_peripheral_base() + 0x9020f0))
#define HDMI_CEC_CNTRL_4           ((volatile uint32_t *)(_get_peripheral_base() + 0x9020f4))
#define HDMI_CEC_CNTRL_5           ((volatile uint32_t *)(_get_peripheral_base() + 0x9020f8))
#define HDMI_CEC_TX_DATA_1         ((volatile uint32_t *)(_get_peripheral_base() + 0x9020fc))
#define HDMI_CEC_TX_DATA_2         ((volatile uint32_t *)(_get_peripheral_base() + 0x902100))
#define HDMI_CEC_TX_DATA_3         ((volatile uint32_t *)(_get_peripheral_base() + 0x902104))
#define HDMI_CEC_TX_DATA_4         ((volatile uint32_t *)(_get_peripheral_base() + 0x902108))
#define HDMI_CEC_RX_DATA_1         ((volatile uint32_t *)(_get_peripheral_base() + 0x90210c))
#define HDMI_CEC_RX_DATA_2         ((volatile uint32_t *)(_get_peripheral_base() + 0x902110))
#define HDMI_CEC_RX_DATA_3         ((volatile uint32_t *)(_get_peripheral_base() + 0x902114))
#define HDMI_CEC_RX_DATA_4         ((volatile uint32_t *)(_get_peripheral_base() + 0x902118))
#define HDMI_TX_PHY_RESET_CTL      ((volatile uint32_t *)(_get_peripheral_base() + 0x9022c0))
#define HDMI_TX_PHY_CTL_0          ((volatile uint32_t *)(_get_peripheral_base() + 0x9022c4))
#define HDMI_CEC_CPU_STATUS        ((volatile uint32_t *)(_get_peripheral_base() + 0x902340))
#define HDMI_CEC_CPU_SET           ((volatile uint32_t *)(_get_peripheral_base() + 0x902344))
#define HDMI_CEC_CPU_CLEAR         ((volatile uint32_t *)(_get_peripheral_base() + 0x902348))
#define HDMI_CEC_CPU_MASK_STATUS   ((volatile uint32_t *)(_get_peripheral_base() + 0x90234c))
#define HDMI_CEC_CPU_MASK_SET      ((volatile uint32_t *)(_get_peripheral_base() + 0x902350))
#define HDMI_CEC_CPU_MASK_CLEAR    ((volatile uint32_t *)(_get_peripheral_base() + 0x902354))
#define HDMI_RAM_PACKET_START      ((volatile uint32_t *)(_get_peripheral_base() + 0x902400))
#define HDMI_RAM_PACKET(x, i)      ((volatile uint32_t *)(_get_peripheral_base() + 0x902400 + (0x24 * (x) + (0x4 * (i)))))

#endif

